In [ ]:
# 라이브러리 불러오기
import numpy
import pandas
import matplotlib.pyplot
import seaborn

In [2]:
numpy.array((2,2))

array([2, 2])

In [1]:
# alias(별칭) 설정
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [4]:
np.array((2,2))

array([2, 2])

In [8]:
array1 = np.array((2, 3))
print(array1)
print(type(array1))

[2 3]
<class 'numpy.ndarray'>


## 1. Numpy란?

In [ ]:
# 1D array
arr1 = np.array([1, 2, 3])
np.shape(arr1)   # shape : 데이터가 몇개인지 확인

(3,)

In [11]:
arr1.shape

(3,)

In [ ]:
# 2D array
arr2 = np.array([[1, 2, 3], 
                 [4, 5, 6]])

np.shape(arr2)   # (2, 3) : 2행 3열

(2, 3)

In [ ]:
#3D array
arr3 = np.array([[[1,2,3],
                  [4,5,6]],
                 [[7,8,9],
                  [10, 11,12]],
                 [[13, 14, 15],
                  [16, 17, 18]]])

arr3.shape   # (3, 2, 3) : 3차원 2행 3열

(3, 2, 3)

------------

## 3-2. 배열(array) 데이터 슬라이싱과 정렬

### 배열 생성하기

In [4]:
mylist = [1, 2, 3]
a = np.array(mylist)
print(type(mylist))
print(a)
print(type(a))

<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>


In [5]:
mylist = [[1, 2,3], [4, 5, 6]]
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6]])

### 데이터 타입 지정

In [6]:
np.array([1, 2, 3], dtype = int)

array([1, 2, 3])

In [7]:
a = np.array([1, 2, 3], dtype = int)
a.dtype

dtype('int64')

In [8]:
np.array([1, 2, 3], dtype = float)

array([1., 2., 3.])

In [9]:
b = np.array([1, 2, 3], dtype = float)
b.dtype

dtype('float64')

In [11]:
np.array(['1', '2', '3'])   #<U1 : 유니코드, 길이가 1인 문자

array(['1', '2', '3'], dtype='<U1')

In [ ]:
np.array(['ab', 'cd', 'ef'])

array(['ab', 'cd', 'ef'], dtype='<U2')

In [13]:
np.array(['1', '2', '3'], dtype = int)

array([1, 2, 3])

### 자체 생성 함수

In [15]:
# 값이 1로 채워진 배열 생성 : ones()
a = np.ones((3, 3))
print(a)
print(a.dtype)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
float64


In [16]:
np.ones((3, 3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [17]:
# 값이 0으로 채워진 배열 생성 : zeros()
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# 단위 행렬 만들기 : eye()
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# 사용자가 지정한 값으로 채워진 배열 생성 : full()
np.full((3, 3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [21]:
# 랜덤 값 : random.rand()
np.random.rand(3,3)

array([[0.06145676, 0.9610377 , 0.71454124],
       [0.82969321, 0.48463857, 0.94653315],
       [0.16640609, 0.83381177, 0.88688182]])

### 등간격 배열 생성 : arange(), linspace()

In [26]:
# arange() : 끝값 포함 X
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(2, 10, 2)      # arange(start, end, skip)

array([2, 4, 6, 8])

In [29]:
# linspace() : 끝값 포함
np.linspace(1, 10, 5)   # linspace(start, end, 요소갯수)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [33]:
# 배열의 모양 바꾸기 : reshape()
a = np.arange(10)
print(a)
print('a: ', a.shape)

b = np.arange(10).reshape(2, 5)
print(b)
print('b: ', b.shape)

[0 1 2 3 4 5 6 7 8 9]
a:  (10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
b:  (2, 5)


In [37]:
c = np.arange(10).reshape(-1, 5)   # 5열로 만들고 행은 알아서 설정
print(c)
print('c: ', c.shape)

d = np.arange(10).reshape(5, -1)   # 5행으로 만들고 열은 알아서 설정
print(d)
print('d: ', d.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
c:  (2, 5)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
d:  (5, 2)


### 슬라이싱

In [38]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [40]:
arr = np.arange(1, 17).reshape(4, -1)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [42]:
# 행 기준 슬라이싱
print(arr[0])
print(arr[0, :])     # 0행의 모든열
print(arr[0, 2:4])   # 0행의 2~3열

[1 2 3 4]
[1 2 3 4]
[3 4]


In [43]:
# 열 기준 슬라이싱
print(arr[:, 0])
print(arr[:, 2])
print(arr[1:3, 2])

[ 1  5  9 13]
[ 3  7 11 15]
[ 7 11]


In [44]:
# 간격을 지정해서 슬라이싱
print(arr[::2])
print(arr[1:3])
print(arr[:, 1:3])

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [45]:
# 마지막열 슬라이싱
print(arr[:, -1])

[ 4  8 12 16]


In [47]:
#0, 1행 과 1, 2열 슬라이싱
print(arr[0:2, 1:3])

[[2 3]
 [6 7]]


### fancy 인덱싱

In [48]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [49]:
# 0행 2행 인덱싱
print(arr[[0, 2], ])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [50]:
# 0, 2, 3행 인덱싱
print(arr[[0, 2, 3], ])

[[ 1  2  3  4]
 [ 9 10 11 12]
 [13 14 15 16]]


In [3]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

arr = np.arange(1, 17).reshape(4, -1)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
# 1행 1열, 2행 3열 인덱싱
print(arr)

print(arr[[1, 2], [1, 3]])   #1행 1열에서 겹친는 부분 + 2행 3열에서 겹치는 부분 출력

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 6 12]


### Boolean 인덱싱

In [21]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [22]:
# boolean 배열
bool = np.array([[True, True, True, True],
                [False, False, False, False],
                [True, True, True, True],
                [False, False, False, False]])

In [23]:
print(arr[bool])   # bool 배열 상 True인 부분만 뽑아서 출력

[ 1  2  3  4  9 10 11 12]


In [24]:
bool2 = np.array([[1, 1, 1, 1],     # 1행 4번, 0행 4번, 1행 4번, 0행 4번 출력
                [0, 0, 0, 0],
                [1, 1, 1, 1],
                [0, 0, 0, 0]])

print(arr[bool2])

[[[5 6 7 8]
  [5 6 7 8]
  [5 6 7 8]
  [5 6 7 8]]

 [[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]

 [[5 6 7 8]
  [5 6 7 8]
  [5 6 7 8]
  [5 6 7 8]]

 [[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]


In [25]:
# boolean 배열 생성
print(arr)

print(arr>10)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[False False False False]
 [False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [26]:
arr[arr<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
#numpy cheat sheet (함수가 정리된 시트 모음)

### 유용한 Numpy 함수
###### numpy cheat sheet (함수가 정리된 시트 모음) 사이트 참고

In [30]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [28]:
# 최소값, 최대값
print(np.min(arr), np.max(arr))
print(arr.min(), arr.max())

1 16
1 16


In [31]:
# 최소값, 최대값 인덱스
print(np.argmin(arr), np.argmax(arr))
print(arr.argmin(), arr.argmax())

0 15
0 15


In [ ]:
# 전체 합, 평균, 중간값
print(np.sum(arr), np.mean(arr), np.median(arr))
print(arr.sum(), arr.mean())   # median()은 넘파이 함수로만 제공

136 8.5 8.5
136 8.5


In [35]:
# 특정 값 인덱스
print(np.where(arr==5))

(array([1]), array([0]))


### 배열차원변환

In [36]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr2 = arr1.reshape(2, 5)
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
# 1. 리스트로 타입을 변환

list = arr1.tolist()
print(list)
print(type(list))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [43]:
list = arr1.reshape(-1).tolist()
print(list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [44]:
# 2. flatten() 메서드 사용
print(arr2)
arr1 = arr2.flatten()
print(arr1)
print(arr1.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
(10,)


### 정렬 : np.sort()

In [46]:
# 1차원 정렬

arr = np.array([3, 6, 9, 1, 2, 4, 7, 8, 5, 10])
print(arr)
print(np.sort(arr))   # 원본 데이터는 변경되지 않음
print(arr)

[ 3  6  9  1  2  4  7  8  5 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 3  6  9  1  2  4  7  8  5 10]


In [ ]:
arr.sort()   # 원본 데이터가 변경됨
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [48]:
# 내림차순으로 정렬

print(np.sort(arr)[::-1])
print(arr)

[10  9  8  7  6  5  4  3  2  1]
[ 1  2  3  4  5  6  7  8  9 10]


In [49]:
# N 차원 정렬

arr = np.random.randint(1, 17, (4, 4))
print(arr)

[[10  6  2  2]
 [ 6 16  6  7]
 [ 2  3  8 16]
 [14 13  8  5]]


In [50]:
# 행 방향(위에서 아래로)

np.sort(arr, axis=0)

array([[ 2,  3,  2,  2],
       [ 6,  6,  6,  5],
       [10, 13,  8,  7],
       [14, 16,  8, 16]], dtype=int32)

In [51]:
np.sort(arr, axis=0)[::-1]

array([[14, 16,  8, 16],
       [10, 13,  8,  7],
       [ 6,  6,  6,  5],
       [ 2,  3,  2,  2]], dtype=int32)

In [52]:
# 열 방향(좌에서 우로)

np.sort(arr, axis=1)

array([[ 2,  2,  6, 10],
       [ 6,  6,  7, 16],
       [ 2,  3,  8, 16],
       [ 5,  8, 13, 14]], dtype=int32)

In [53]:
np.sort(arr, axis=1)[::-1]

array([[ 5,  8, 13, 14],
       [ 2,  3,  8, 16],
       [ 6,  6,  7, 16],
       [ 2,  2,  6, 10]], dtype=int32)

## 3-3. 행렬(matrix) 연산과 성능

In [54]:
a = np.arange(1, 7).reshape(-1, 3)
print(a)
b = np.arange(7, 13).reshape(-1, 2)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [55]:
# 행렬 합은 전치(transpose)하여 shape을 맞춘 후 연산

print(a.shape)
print('-'*10)
print(b.shape)

(2, 3)
----------
(3, 2)


In [ ]:
# a를 전치 (행 / 열 상호 변경)

print(a.T)
print(a.T.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [ ]:
# 전치된 a와 b를 덧셈, 뺄셈 연산
print(a)
print(b)
print('-'*10)
print(a.T+b)
print(b-a.T)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
----------
[[ 8 12]
 [11 15]
 [14 18]]
[[6 4]
 [7 5]
 [8 6]]


In [63]:
# 행렬의 곱
print(a)
print(b)

print('-'*10)

c = a @ b
print(c)

print('-'*10)

d = np.dot(a, b)
print(d)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
----------
[[ 58  64]
 [139 154]]
----------
[[ 58  64]
 [139 154]]


In [64]:
arr1 = arr2 = np.arange(1, 17).reshape(4, 4)
print(arr1)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [65]:
arr1 + arr2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [66]:
arr1 - arr2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [69]:
# element-wise 연산(shape이 같아야 연산 가능)
arr1 * arr2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144],
       [169, 196, 225, 256]])

In [68]:
arr1 / arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [72]:
# 내적 연산(Dot product)

print(np.dot(arr1, arr2))

print(arr1@arr2)

[[ 90 100 110 120]
 [202 228 254 280]
 [314 356 398 440]
 [426 484 542 600]]
[[ 90 100 110 120]
 [202 228 254 280]
 [314 356 398 440]
 [426 484 542 600]]


In [73]:
arr1 = np.arange(1, 9).reshape(2, -1)
arr2 = np.array([[1, 2],
                 [5, 6],
                 [9, 10],
                 [13, 14]])
print(arr1)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]


In [ ]:
np.dot(arr1, arr2)

array([[ 90, 100],
       [202, 228]])

### 행렬 집계 함수

In [76]:
arr = np.arange(1, 17).reshape(4, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [77]:
# 합계 - 전체

np.sum(arr)

np.int64(136)

In [78]:
# 합계 - 행방향(위에서 아래로)

np.sum(arr, axis=0)

array([28, 32, 36, 40])

In [79]:
# 합계 - 열방향(좌에서 우로)

np.sum(arr, axis=1)

array([10, 26, 42, 58])

### Broadcasting 연산

In [82]:
arr3d = np.arange(0, 24).reshape(-1, 4, 2)
arr2d = np.arange(0, 8).reshape(-1, 2)

print(arr3d)
print('-'*10)
print(arr2d)
print('-'*10)
print(np.shape(arr3d), np.shape(arr2d))

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
----------
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
----------
(3, 4, 2) (4, 2)


In [83]:
arr3d + arr2d

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14]],

       [[ 8, 10],
        [12, 14],
        [16, 18],
        [20, 22]],

       [[16, 18],
        [20, 22],
        [24, 26],
        [28, 30]]])

In [84]:
print(arr2d)
print('-'*10)
print(arr2d + 10)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
----------
[[10 11]
 [12 13]
 [14 15]
 [16 17]]


In [85]:
print(arr2d)
print('-'*10)
print(arr2d * 10)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
----------
[[ 0 10]
 [20 30]
 [40 50]
 [60 70]]


In [86]:
print(arr2d)
print('-'*10)
print(arr2d / 10)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
----------
[[0.  0.1]
 [0.2 0.3]
 [0.4 0.5]
 [0.6 0.7]]
