In [ ]:
# 라이브러리 불러오기
import numpy
import pandas
import matplotlib.pyplot
import seaborn

In [2]:
numpy.array((2,2))

array([2, 2])

In [1]:
# alias(별칭) 설정
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [4]:
np.array((2,2))

array([2, 2])

In [8]:
array1 = np.array((2, 3))
print(array1)
print(type(array1))

[2 3]
<class 'numpy.ndarray'>


## 1. Numpy란?

In [ ]:
# 1D array
arr1 = np.array([1, 2, 3])
np.shape(arr1)   # shape : 데이터가 몇개인지 확인

(3,)

In [11]:
arr1.shape

(3,)

In [ ]:
# 2D array
arr2 = np.array([[1, 2, 3], 
                 [4, 5, 6]])

np.shape(arr2)   # (2, 3) : 2행 3열

(2, 3)

In [ ]:
#3D array
arr3 = np.array([[[1,2,3],
                  [4,5,6]],
                 [[7,8,9],
                  [10, 11,12]],
                 [[13, 14, 15],
                  [16, 17, 18]]])

arr3.shape   # (3, 2, 3) : 3차원 2행 3열

(3, 2, 3)

------------

## 3-2. 배열(array) 데이터 슬라이싱과 정렬

### 배열 생성하기

In [4]:
mylist = [1, 2, 3]
a = np.array(mylist)
print(type(mylist))
print(a)
print(type(a))

<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>


In [5]:
mylist = [[1, 2,3], [4, 5, 6]]
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6]])

### 데이터 타입 지정

In [6]:
np.array([1, 2, 3], dtype = int)

array([1, 2, 3])

In [7]:
a = np.array([1, 2, 3], dtype = int)
a.dtype

dtype('int64')

In [8]:
np.array([1, 2, 3], dtype = float)

array([1., 2., 3.])

In [9]:
b = np.array([1, 2, 3], dtype = float)
b.dtype

dtype('float64')

In [11]:
np.array(['1', '2', '3'])   #<U1 : 유니코드, 길이가 1인 문자

array(['1', '2', '3'], dtype='<U1')

In [ ]:
np.array(['ab', 'cd', 'ef'])

array(['ab', 'cd', 'ef'], dtype='<U2')

In [13]:
np.array(['1', '2', '3'], dtype = int)

array([1, 2, 3])

### 자체 생성 함수

In [15]:
# 값이 1로 채워진 배열 생성 : ones()
a = np.ones((3, 3))
print(a)
print(a.dtype)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
float64


In [16]:
np.ones((3, 3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [17]:
# 값이 0으로 채워진 배열 생성 : zeros()
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# 단위 행렬 만들기 : eye()
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# 사용자가 지정한 값으로 채워진 배열 생성 : full()
np.full((3, 3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [21]:
# 랜덤 값 : random.rand()
np.random.rand(3,3)

array([[0.06145676, 0.9610377 , 0.71454124],
       [0.82969321, 0.48463857, 0.94653315],
       [0.16640609, 0.83381177, 0.88688182]])

### 등간격 배열 생성 : arange(), linspace()

In [26]:
# arange() : 끝값 포함 X
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(2, 10, 2)      # arange(start, end, skip)

array([2, 4, 6, 8])

In [29]:
# linspace() : 끝값 포함
np.linspace(1, 10, 5)   # linspace(start, end, 요소갯수)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [33]:
# 배열의 모양 바꾸기 : reshape()
a = np.arange(10)
print(a)
print('a: ', a.shape)

b = np.arange(10).reshape(2, 5)
print(b)
print('b: ', b.shape)

[0 1 2 3 4 5 6 7 8 9]
a:  (10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
b:  (2, 5)


In [37]:
c = np.arange(10).reshape(-1, 5)   # 5열로 만들고 행은 알아서 설정
print(c)
print('c: ', c.shape)

d = np.arange(10).reshape(5, -1)   # 5행으로 만들고 열은 알아서 설정
print(d)
print('d: ', d.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
c:  (2, 5)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
d:  (5, 2)


### 슬라이싱

In [38]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [40]:
arr = np.arange(1, 17).reshape(4, -1)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [42]:
# 행 기준 슬라이싱
print(arr[0])
print(arr[0, :])     # 0행의 모든열
print(arr[0, 2:4])   # 0행의 2~3열

[1 2 3 4]
[1 2 3 4]
[3 4]


In [43]:
# 열 기준 슬라이싱
print(arr[:, 0])
print(arr[:, 2])
print(arr[1:3, 2])

[ 1  5  9 13]
[ 3  7 11 15]
[ 7 11]


In [44]:
# 간격을 지정해서 슬라이싱
print(arr[::2])
print(arr[1:3])
print(arr[:, 1:3])

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [45]:
# 마지막열 슬라이싱
print(arr[:, -1])

[ 4  8 12 16]


In [47]:
#0, 1행 과 1, 2열 슬라이싱
print(arr[0:2, 1:3])

[[2 3]
 [6 7]]


## fancy 인덱싱

In [48]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [49]:
# 0행 2행 인덱싱
print(arr[[0, 2], ])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [50]:
# 0, 2, 3행 인덱싱
print(arr[[0, 2, 3], ])

[[ 1  2  3  4]
 [ 9 10 11 12]
 [13 14 15 16]]
